export const SET_UP = 'SET_UP'
export const REST_CALL = 'REST_CALL'
export const GET_ARTICLE_BY_SLUG = 'GET_ARTICLE_BY_SLUG'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORY_PAGE = 'GET_CATEGORY_PAGE'
export const CHANGE_PAGE_TITLE = 'CHANGE_PAGE_TITLE'
export const GET_SHARED_COUNT = "GET_SHARED_COUNT"
